on:
    push:
      branches:
        - main
        - master
        - develop
        - 'releases/**'
    pull_request:
      branches:
        - main
        - master
        - develop
        - 'releases/**'
      types:
        - opened
        - synchronize
        - reopened
  
  name: Main Workflow
  
  jobs:
    sonarqube:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
  
        - name: Set up Java
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '11'
  
        - name: SonarQube Scan
          uses: sonarsource/sonarqube-scan-action@v2.1.0
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            SONAR_SCANNER_OPTS: '-Xmx1024m'
            SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
  
        - name: Check SonarQube Quality Gate
          id: quality_gate
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          run: |
            status=$(curl -s "${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=SNHS1998_SonarQube-GitHubActions" -u "${SONAR_TOKEN}:")
            coverage=$(echo "$status" | jq -r '.projectStatus.conditions[] | select(.metricKey == "new_coverage") | .actualValue')
  
            echo "Current New Code Coverage: $coverage%"
  
            if (( $(echo "$coverage == null" | bc -l) )); then
              echo "New code coverage information is not available."
              exit 1
            elif (( $(echo "$coverage < 80" | bc -l) )); then
              echo "New code coverage is less than 80%. Failing the build."
              exit 1
            else
              echo "New code coverage is sufficient. Proceeding with the build."
            fi
  
        - name: Fail build on Quality Gate status
          if: steps.quality_gate.outcome != 'success'
          run: exit 1
  